config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :people
  resources :follows

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/user/:id/settings', to: "users#settings", as: :user_settings
  root 'static_pages#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :person
  has_many :follows, class_name: "Follow", foreign_key: :follower_id
  has_many :followees, through: :follows

  def self.find_or_create_from_auth_hash(auth_hash, user = nil)
    if user
      update_authorizations(auth_hash, user)
    else
      if auth_hash[:provider] == "twitter"
        if User.find_by(twitter_uid: auth_hash[:uid])
         @user = User.find_by(twitter_uid: auth_hash[:uid])
         @user.twitter_auth_token = auth_hash["credentials"]["token"]
        else
          @user = create! do |user|
            user.twitter_provider = auth_hash["provider"]
            user.twitter_uid = auth_hash["uid"]
            user.twitter_name = auth_hash["info"]["name"]
            user.twitter_auth_token = auth_hash["credentials"]["token"]
          end
        end
      elsif auth_hash[:provider] == "facebook"
        if User.find_by(facebook_uid: auth_hash[:uid])
         @user = User.find_by(facebook_uid: auth_hash[:uid])
         @user.facebook_auth_token = auth_hash["credentials"]["token"]
        else
          @user = create! do |user|
            user.facebook_provider = auth_hash["provider"]
            user.facebook_uid = auth_hash["uid"]
            user.facebook_name = auth_hash["info"]["name"]
            user.facebook_auth_token = auth_hash["credentials"]["token"]
          end
        end

      elsif auth_hash[:provider] == "instagram"
        if User.find_by(instagram_uid: auth_hash[:uid])
         @user = User.find_by(instagram_uid: auth_hash[:uid])
         @user.instagram_auth_token = auth_hash["credentials"]["token"]
        else
          @user = create! do |user|
            user.instagram_provider = auth_hash["provider"]
            user.instagram_uid = auth_hash["uid"]
            user.instagram_name = auth_hash["info"]["name"]
            user.instagram_auth_token = auth_hash["credentials"]["token"]
          end
        end
      else
      # throw an error
      "error"
      end
    end
  @user
  end


  def self.update_authorizations(auth_hash, user)
    @user = user
    if auth_hash[:provider] == "twitter"
      @user.twitter_provider = auth_hash["provider"]
      @user.twitter_uid = auth_hash["uid"]
      @user.twitter_name = auth_hash["info"]["name"]
      @user.twitter_auth_token = auth_hash["credentials"]["token"]
    elsif auth_hash[:provider] == "facebook"
      @user.facebook_provider = auth_hash["provider"]
      @user.facebook_uid = auth_hash["uid"]
      @user.facebook_name = auth_hash["info"]["name"]
      @user.facebook_auth_token = auth_hash["credentials"]["token"]
    elsif auth_hash[:provider] == "instagram"
      @user.instagram_provider = auth_hash["provider"]
      @user.instagram_uid = auth_hash["uid"]
      @user.instagram_name = auth_hash["info"]["name"]
      @user.instagram_auth_token = auth_hash["credentials"]["token"]
    else
      # throw an error
      "error"
    end
    @user.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # @instagram = Instagram.user_recent_media("49493754", {:count => 1})
  end

  def create
    @user = User.new(user_name: params[:user][:user_name])
    render new_user_path
  end

  def show
    @user = User.find(params[:id])
    @posts = []
    if @user.instagram_uid
      @instagram = InstagramConnection.new(@user)
      @instagram_posts = @instagram.get_post_details(@user) 
      @posts += @instagram_posts
    end

    if @user.twitter_uid
      @tweets = TwitterConnection.new(@user).twitter_connect
      @posts += @tweets
    end

    if @user.facebook_uid
      @facebook_posts = FacebookConnection.new(@user).get_posts 
      @posts += @facebook_posts
    end
    @posts = @posts.sort_by{|post| post[:post_time] }.reverse.slice(0,20)
  end

  def edit
    @user = User.find(params[:id])
    @follows = @user.follows
  end

  def settings

  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_authorize.html.erb
<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                  <h1>Add accounts here.</h1>

                  <%= link_to 'facebook', '/auth/facebook', {class: "btn btn-default btn-lg"}%>
                  <%= link_to 'twitter', '/auth/twitter', {class: "btn btn-default btn-lg"}%>
                  <%= link_to 'instagram', '/auth/instagram', {class: "btn btn-default btn-lg"}%>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/users/_delete_follows.html.erb
<h1>Remove friends here - from the partial</h1>
<%@follows.each do |follow| %>
    <p><%= follow.name || follow.facebook_handle || follow.twitter_handle %></p>
<%end %>

app/views/users/_manage_follows.html.erb
<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <% if !(current_user.facebook_uid && current_user.twitter_uid && current_user.instagram_uid) %>
          <h3>Authorize your accounts.</h3>
          <% if current_user.facebook_uid %>
          <%= link_to 'facebook', '/auth/facebook', {class: "btn btn-default btn-lg disabled"}%>
          <% else %>
          <%= link_to 'facebook', '/auth/facebook', {class: "btn btn-default btn-lg"}%>
          <% end %>
          <% if current_user.twitter_uid %>
          <%= link_to 'twitter', '/auth/twitter', {class: "btn btn-default btn-lg disabled"}%>
          <% else %>
          <%= link_to 'twitter', '/auth/twitter', {class: "btn btn-default btn-lg"}%>
          <% end %>

          <% if current_user.instagram_uid %>
          <%= link_to 'instagram', '/auth/instagram', {class: "btn btn-default btn-lg disabled"}%>
          <% else %>
          <%= link_to 'instagram', '/auth/instagram', {class: "btn btn-default btn-lg"}%>
          <% end %>
          <% end %>
          <br><br><br><br>

          <h1>add friends.</h1>
          <div class="row">
            <%= form_for Person.new  do |f| %>
            <div class="form-group col-xs-4">    
              <%= f.text_field :facebook_handle, placeholder: "facebook", class: 'form-control input-lg'%>
            </div>  
            <div class="form-group col-xs-4">
              <%= f.text_field :twitter_handle, placeholder: "twitter handle", class: 'form-control input-lg'%>
            </div>
            <div class="form-group col-xs-4">
              <%= f.text_field :instagram_handle, placeholder: "instagram", class: 'form-control input-lg'%>
              <br><br>
            </div>
            <%= f.submit "ADD FRIENDS", {class: 'btn btn-default'}%>
          </div>
          <br><br><br><br>
          <h2><%= "remove friends." if !@follows.empty? %></h2>
          <div class "row">
            <%@follows.each do |follow| %>
            <% person = Person.find(follow.followee_id) %>
            
              <%= link_to 'x', follow_path(follow), method: :delete %>
              <%= person.name || person.facebook_handle || person.twitter_handle|| person.instagram_handle %>
              &nbsp;&nbsp;&nbsp;

            <%end %>
          </div>
          <% end %>
          <br>
        </div>
      </div>
    </div>
  </div>
  
</header>

app/views/users/edit.html.erb
<%= render 'manage_follows' %>

app/views/users/index.html.erb
<% form_tag projects_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/users/new.html.erb
<%= render 'authorize' %>

app/views/users/show.html.erb
<header class="content">
  <div class="intro-body">
    <div class="container-fluid">
      <div class="row feed">
          <div class="grid">

              <% if @posts %>
               <!--  <h2 class="text-center">Latest posts: </h2>  -->
                      <% @posts.each do |post|%>
                        <div class="grid-item">
                             <div class="node" >
                              <%= image_tag(post[:photo_uri], {class: "center-block img-responsive"}) %> <br>
                              <a href="<%=post[:uri] %>">@<%= post[:handle] %> </a> <br>
                              <h4><%= post[:text] %></h4>
                            </div>
                        </div> <!-- grid item end -->
                      <% end %> 
                    <br>    
                <% else %>
                <h1>You're not following anyone. <a href="#"> Add friends!</a></h1>
                <% end %> <!-- end if @posts -->
          </div> <!-- grid end -->

      </div>
    </div>
  </div>
</header>